@extends('layouts.app')
@section('title', 'Detail Pengajuan')
@section('content')
    <div class="page-heading heading-with-action"><div><p class="section-kicker">Detail sertifikat</p><h1>{{ $submission->activity_name }}</h1><p>Tersimpan {{ $submission->submitted_at?->translatedFormat('d F Y, H:i') }}</p></div><span class="status status-approved large">Tersimpan</span></div>
    @if($submission->admin_note)<div class="review-note"><strong>Catatan admin</strong><p>{{ $submission->admin_note }}</p></div>@endif
    <div class="content-grid detail-grid">
        <section class="panel"><div class="panel-head"><div><h2>Informasi kegiatan</h2><p>Data yang digunakan dalam proses verifikasi</p></div></div><dl class="detail-list"><div><dt>Kategori</dt><dd>{{ $submission->rule->category }}</dd></div><div><dt>Jenis kegiatan</dt><dd>{{ $submission->rule->label() }}</dd></div><div><dt>Penyelenggara</dt><dd>{{ $submission->organizer }}</dd></div><div><dt>Periode</dt><dd>{{ $submission->started_at->translatedFormat('d M Y') }}{{ $submission->ended_at ? ' sampai '.$submission->ended_at->translatedFormat('d M Y') : '' }}</dd></div><div><dt>Nomor sertifikat</dt><dd>{{ $submission->certificate_number ?: 'Tidak dicantumkan' }}</dd></div><div><dt>Bukti</dt><dd>@if($submission->evidence_path)<a class="text-link" href="{{ route('evidence.download', $submission) }}">{{ $submission->evidence_original_name }}</a>@else<span class="muted">Data simulasi, berkas tidak tersedia</span>@endif</dd></div></dl></section>
        <aside class="panel score-panel"><div class="score-number"><small>Bobot kegiatan</small><strong>{{ $submission->approved_points }}</strong><span>poin</span></div><p>Sertifikat sudah masuk ke rekap dan dapat dicantumkan pada SKPI.</p></aside>
    </div>
    <div class="record-actions"><a href="{{ route('student.submissions.edit', $submission) }}" class="button button-secondary">Ubah sertifikat</a><form method="POST" action="{{ route('student.submissions.destroy', $submission) }}" data-confirm="Hapus sertifikat ini beserta berkas buktinya? Pengajuan SKPI aktif akan dibatalkan agar dapat diajukan ulang.">@csrf @method('DELETE')<button class="button button-danger" type="submit">Hapus sertifikat</button></form></div>
    @if($submission->decisions->isNotEmpty())<section class="panel decision-history"><div class="panel-head"><div><h2>Riwayat keputusan</h2><p>Perubahan tercatat pada pengajuan yang sama</p></div></div>@foreach($submission->decisions->sortByDesc('created_at') as $decision)<div class="decision-row"><span class="status status-{{ $decision->decision }}">{{ ucfirst($decision->decision) }}</span><div><strong>{{ $decision->admin->name }}</strong><p>{{ $decision->note ?: 'Disetujui sesuai pedoman.' }}</p></div><time>{{ $decision->created_at->translatedFormat('d M Y, H:i') }}</time></div>@endforeach</section>@endif
@endsection
