@extends('layouts.app')
@section('title', 'Verifikasi Sertifikat')
@section('content')
    <div class="page-heading"><p class="section-kicker">Antrean pemeriksaan</p><h1>Verifikasi sertifikat</h1><p>Periksa identitas, bukti, jenis kegiatan, dan kesesuaiannya dengan pedoman poin.</p></div>
    <form method="GET" class="filter-bar admin-filter"><label class="search-field">@include('partials.icon', ['name' => 'search'])<input type="search" name="q" value="{{ request('q') }}" placeholder="Cari nama mahasiswa"></label><label class="select-filter">@include('partials.icon', ['name' => 'filter'])<select name="status"><option value="">Semua status</option>@foreach(['pending'=>'Menunggu','revision'=>'Perlu revisi','approved'=>'Disetujui','rejected'=>'Ditolak'] as $value=>$label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></label><button class="button button-secondary" type="submit">Terapkan filter</button>@if(request()->hasAny(['q','status']))<a href="{{ route('admin.submissions.index') }}" class="text-link">Reset</a>@endif</form>
    <section class="panel panel-table">
        @if($submissions->isEmpty())<div class="empty-state">@include('partials.icon', ['name' => 'file'])<h3>Tidak ada pengajuan</h3><p>Ubah filter untuk melihat data lain.</p></div>@else
        <div class="table-wrap"><table><thead><tr><th>Mahasiswa</th><th>Kegiatan</th><th>Kategori</th><th>Poin</th><th>Status</th><th></th></tr></thead><tbody>@foreach($submissions as $submission)<tr><td><strong>{{ $submission->user->name }}</strong><small>{{ $submission->user->profile?->nim }} · {{ $submission->user->profile?->studyProgram?->code }}</small></td><td><strong>{{ $submission->activity_name }}</strong><small>{{ $submission->organizer }}</small></td><td>{{ $submission->rule->subcategory }}</td><td>{{ $submission->estimated_points }}</td><td><span class="status status-{{ $submission->status }}">{{ match($submission->status) {'pending'=>'Menunggu','revision'=>'Perlu revisi','approved'=>'Disetujui','rejected'=>'Ditolak','draft'=>'Draf'} }}</span></td><td><a href="{{ route('admin.submissions.show', $submission) }}" class="table-action" aria-label="Periksa pengajuan">@include('partials.icon', ['name' => 'chevron'])</a></td></tr>@endforeach</tbody></table></div><div class="pagination">{{ $submissions->links() }}</div>@endif
    </section>
@endsection
