@extends('layouts.app')
@section('title', 'Sertifikat Masuk')
@section('context', 'Administrasi Sertifikat')
@section('content')
    <div class="page-heading heading-with-action"><div><p class="section-kicker">Kotak masuk sertifikat</p><h1>Sertifikat mahasiswa</h1><p>Setiap unggahan langsung aktif untuk pengajuan SKPI. Gunakan status pemeriksaan untuk memisahkan data baru dan yang sudah dicek.</p></div><a href="{{ route('admin.submissions.create') }}" class="button button-secondary">Tambah sertifikat</a></div>
    <div class="inbox-summary" aria-label="Ringkasan sertifikat"><div><span>Belum dicek</span><strong>{{ $newCount }}</strong></div><p>Pemeriksaan admin tidak menahan poin atau pengajuan SKPI mahasiswa.</p></div>
    <form method="GET" class="filter-bar admin-filter"><label class="search-field">@include('partials.icon', ['name' => 'search'])<input type="search" name="q" value="{{ request('q') }}" placeholder="Nama, NIM, kegiatan, atau nomor sertifikat"></label><label class="select-filter">@include('partials.icon', ['name' => 'filter'])<select name="review"><option value="">Semua pemeriksaan</option><option value="new" @selected(request('review') === 'new')>Belum dicek</option><option value="checked" @selected(request('review') === 'checked')>Sudah dicek</option></select></label><label class="select-filter">@include('partials.icon', ['name' => 'filter'])<select name="category"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category }}" @selected(request('category') === $category)>{{ $category }}</option>@endforeach</select></label><button class="button button-secondary" type="submit">Terapkan filter</button>@if(request()->hasAny(['q','review','category']))<a href="{{ route('admin.submissions.index') }}" class="text-link">Reset</a>@endif</form>
    <section class="panel panel-table">
        @if($submissions->isEmpty())<div class="empty-state">@include('partials.icon', ['name' => 'certificate'])<h3>Tidak ada sertifikat pada filter ini</h3><p>Ubah filter atau tunggu unggahan baru dari mahasiswa.</p></div>@else
        <div class="table-wrap"><table><thead><tr><th>Mahasiswa</th><th>Kegiatan</th><th>Kategori</th><th>Masuk</th><th>Pemeriksaan</th><th></th></tr></thead><tbody>@foreach($submissions as $submission)<tr><td><strong>{{ $submission->user->name }}</strong><small>{{ $submission->user->profile?->nim }} · {{ $submission->user->profile?->studyProgram?->code }}</small></td><td><strong>{{ $submission->activity_name }}</strong><small>{{ $submission->organizer }} · {{ $submission->approved_points ?? $submission->estimated_points }} poin</small></td><td>{{ $submission->rule->category }}</td><td>{{ $submission->submitted_at?->translatedFormat('d M Y, H:i') }}</td><td>@if($submission->admin_checked_at)<span class="status status-approved">Sudah dicek</span><small>{{ $submission->checker?->name }} · {{ $submission->admin_checked_at->translatedFormat('d M Y') }}</small>@else<span class="status status-pending">Baru</span><small>Belum dibuka admin</small>@endif</td><td><a href="{{ route('admin.submissions.show', $submission) }}" class="table-action" aria-label="Cek sertifikat {{ $submission->activity_name }}">@include('partials.icon', ['name' => 'chevron'])</a></td></tr>@endforeach</tbody></table></div><div class="pagination">{{ $submissions->links() }}</div>@endif
    </section>
@endsection
