@extends('layouts.app')
@section('title', 'Cek Sertifikat')
@section('context', 'Administrasi Sertifikat')
@section('content')
    <div class="page-heading heading-with-action"><div><p class="section-kicker">Detail sertifikat</p><h1>{{ $submission->activity_name }}</h1><p>{{ $submission->user->name }} · {{ $submission->user->profile?->nim }}</p></div><span class="status {{ $submission->admin_checked_at ? 'status-approved' : 'status-pending' }} large">{{ $submission->admin_checked_at ? 'Sudah dicek' : 'Baru masuk' }}</span></div>
    <div class="verification-layout">
        <section class="panel"><div class="panel-head"><div><h2>Data sertifikat</h2><p>Data ini sudah langsung aktif pada rekap mahasiswa dan syarat pengajuan SKPI.</p></div></div><dl class="detail-list"><div><dt>Mahasiswa</dt><dd>{{ $submission->user->name }}<small>{{ $submission->user->profile?->studyProgram?->name }}</small></dd></div><div><dt>Kategori</dt><dd>{{ $submission->rule->category }}</dd></div><div><dt>Aturan kegiatan</dt><dd>{{ $submission->rule->label() }}</dd></div><div><dt>Penyelenggara</dt><dd>{{ $submission->organizer }}</dd></div><div><dt>Tanggal</dt><dd>{{ $submission->started_at->translatedFormat('d F Y') }}{{ $submission->ended_at ? ' sampai '.$submission->ended_at->translatedFormat('d F Y') : '' }}</dd></div><div><dt>Nomor sertifikat</dt><dd>{{ $submission->certificate_number ?: 'Tidak dicantumkan' }}</dd></div><div><dt>Bobot kegiatan</dt><dd>{{ $submission->approved_points ?? $submission->estimated_points }} poin</dd></div><div><dt>Masuk sistem</dt><dd>{{ $submission->submitted_at?->translatedFormat('d F Y, H:i') }}</dd></div></dl>
            @if($submission->verification_url)<p class="verification-link"><strong>Tautan verifikasi</strong><a href="{{ $submission->verification_url }}" target="_blank" rel="noopener noreferrer">Buka tautan verifikasi</a></p>@endif
            @if($submission->evidence_path)<a href="{{ route('evidence.download', $submission) }}" class="evidence-file">@include('partials.icon', ['name' => 'file'])<span><strong>{{ $submission->evidence_original_name }}</strong><small>Unduh untuk memeriksa dokumen</small></span>@include('partials.icon', ['name' => 'download'])</a>@else<div class="evidence-file unavailable">@include('partials.icon', ['name' => 'file'])<span><strong>Berkas tidak tersedia</strong><small>Data ini tidak mempunyai lampiran.</small></span></div>@endif
        </section>
        <aside class="panel decision-panel"><div class="rule-score"><small>Status mahasiswa</small><strong>Aktif</strong><span>{{ $submission->approved_points ?? $submission->estimated_points }} poin masuk rekap</span></div><div class="decision-rule"><strong>Pemeriksaan admin</strong><p>{{ $submission->admin_checked_at ? 'Dicek oleh '.$submission->checker?->name.' pada '.$submission->admin_checked_at->translatedFormat('d F Y, H:i').'.' : 'Belum ditandai sudah diperiksa. Status ini tidak menghambat mahasiswa.' }}</p></div>
            @unless($submission->admin_checked_at)<form method="POST" action="{{ route('admin.submissions.check', $submission) }}">@csrf @method('PUT')<button class="button button-primary button-block" type="submit">Tandai sudah dicek</button></form>@endunless
            <a class="button button-secondary button-block" href="{{ route('admin.submissions.edit', $submission) }}">Ubah data sertifikat</a>
            <form method="POST" action="{{ route('admin.submissions.destroy', $submission) }}" data-confirm="Hapus sertifikat ini beserta berkas buktinya? Tindakan ini tidak dapat dibatalkan.">@csrf @method('DELETE')<button class="button button-danger button-block" type="submit">Hapus sertifikat</button></form>
        </aside>
    </div>
@endsection
